spring.application.name=BiblioTec
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotec_deborasthefany
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

<<<<<<< HEAD

=======
>>>>>>> 1c7dcda9b290a01ba9d311ff396fba0dbb6661df
